"""Scene-level settings for the Marble Allstars tools."""

import bpy
from bpy.props import (
    BoolProperty,
    EnumProperty,
    FloatProperty,
    IntProperty,
    PointerProperty,
    StringProperty,
)

# Presets are deliberately approximate. Use "Export / Import settings" in the
# Level Design panel to keep the numbers in sync with the real Godot project.
PRESETS = {
    "GODOT": {
        "label": "Godot default (9.8 gravity)",
        "gravity": 9.8,
        "accel": 25.0,
        "air_accel": 6.0,
        "max_speed": 12.0,
        "jump_speed": 6.0,
        "bounce": 0.15,
        "friction": 1.2,
        "rb_friction": 0.5,
        "rb_bounciness": 0.1,
    },
    "MARBLE_BLAST": {
        "label": "Marble Blast style (snappy)",
        "gravity": 20.0,
        "accel": 40.0,
        "air_accel": 8.0,
        "max_speed": 15.0,
        "jump_speed": 7.5,
        "bounce": 0.45,
        "friction": 1.0,
        "rb_friction": 0.6,
        "rb_bounciness": 0.4,
    },
    "FLOATY": {
        "label": "Floaty (low gravity)",
        "gravity": 5.0,
        "accel": 18.0,
        "air_accel": 6.0,
        "max_speed": 10.0,
        "jump_speed": 5.0,
        "bounce": 0.3,
        "friction": 0.8,
        "rb_friction": 0.4,
        "rb_bounciness": 0.3,
    },
}

# Custom property names used to tag generated / tagged objects.
ROLE_PROP = "marble_tools_role"          # SPAWN, MARBLE, PATH, CHECKPOINT, FINISH, ARC, TARGET
AUTO_RB_PROP = "marble_tools_auto_rb"    # True on level objects we gave a passive rigid body


class MarbleToolsSettings(bpy.types.PropertyGroup):
    # ------------------------------------------------------------------ setup
    level_collection: PointerProperty(
        name="Level Collection",
        description="Collection holding the level geometry. Leave empty to use every visible mesh "
                    "that is not generated by this add-on",
        type=bpy.types.Collection,
    )
    marble_radius: FloatProperty(
        name="Marble Radius", default=0.5, min=0.01, soft_max=5.0, unit="LENGTH",
        description="Radius of the test marble (match the marble in the game)",
    )
    marble_mass: FloatProperty(name="Mass", default=1.0, min=0.001, soft_max=100.0)
    kill_z: FloatProperty(
        name="Kill Z", default=-50.0, soft_min=-1000.0, soft_max=1000.0, unit="LENGTH",
        description="Marbles that fall below this height count as 'fell off the level'",
    )
    preset: EnumProperty(
        name="Preset",
        items=[(key, val["label"], "") for key, val in PRESETS.items()],
        default="GODOT",
    )

    # ------------------------------------------------------------ drop tester
    launch_speed: FloatProperty(
        name="Launch Speed", default=0.0, min=0.0, soft_max=60.0,
        description="Initial speed along the spawn empty's local +Y axis (green arrow). 0 = plain drop",
    )
    drop_count: IntProperty(
        name="Marbles", default=1, min=1, max=25,
        description="Drop several marbles spread along the spawn's local X axis to test ramp width",
    )
    drop_spread: FloatProperty(
        name="Spread", default=1.0, min=0.0, soft_max=20.0, unit="LENGTH",
        description="Total width the marbles are spread over (only when Marbles > 1)",
    )
    sim_frames: IntProperty(
        name="Sim Frames", default=300, min=10, max=5000,
        description="How many frames to simulate (kept in memory only, never written to disk)",
    )
    substeps: IntProperty(
        name="Substeps / Frame", default=10, min=1, max=100,
        description="Rigid body substeps per frame. Raise if fast marbles tunnel through thin geometry",
    )
    rb_friction: FloatProperty(name="Friction", default=0.5, min=0.0, max=1.0)
    rb_bounciness: FloatProperty(name="Bounciness", default=0.1, min=0.0, max=1.0)
    trace_path: BoolProperty(
        name="Trace Path", default=True,
        description="Create a curve showing where each marble went",
    )
    keep_previous: BoolProperty(
        name="Keep Previous", default=False,
        description="Keep marbles and paths from earlier drops instead of replacing them",
    )
    auto_play: BoolProperty(
        name="Play After Drop", default=True,
        description="Start timeline playback after the drop so you can watch it",
    )
    drop_result: StringProperty(name="Last Drop", default="")

    # --------------------------------------------------------------- playtest
    gravity: FloatProperty(name="Gravity", default=9.8, min=0.0, soft_max=50.0)
    accel: FloatProperty(
        name="Ground Accel", default=25.0, min=0.0, soft_max=100.0,
        description="Acceleration from player input while on the ground (m/s²)",
    )
    air_accel: FloatProperty(
        name="Air Accel", default=6.0, min=0.0, soft_max=50.0,
        description="Acceleration from player input while airborne (m/s²)",
    )
    max_speed: FloatProperty(
        name="Max Input Speed", default=12.0, min=0.1, soft_max=60.0,
        description="Input stops accelerating past this speed (ramps and gravity can still go faster)",
    )
    jump_speed: FloatProperty(name="Jump Speed", default=6.0, min=0.0, soft_max=30.0)
    bounce: FloatProperty(
        name="Bounce", default=0.15, min=0.0, max=1.0,
        description="Restitution when hitting surfaces (0 = no bounce)",
    )
    friction: FloatProperty(
        name="Rolling Friction", default=1.2, min=0.0, soft_max=10.0,
        description="Damping applied to the velocity along the surface while grounded",
    )
    slope_limit: FloatProperty(
        name="Slope Limit", default=50.0, min=0.0, max=89.0,
        description="Surfaces steeper than this (degrees) do not count as ground for jumping",
    )
    physics_hz: IntProperty(
        name="Physics Hz", default=60, min=30, max=240,
        description="Fixed physics tick rate (Godot default is 60)",
    )
    physics_substeps: IntProperty(
        name="Substeps", default=4, min=1, max=16,
        description="Collision substeps per tick. Raise if the marble clips through thin walls",
    )
    cam_distance: FloatProperty(name="Camera Distance", default=6.0, min=0.5, soft_max=50.0)
    cam_height: FloatProperty(name="Camera Height", default=1.5, min=-10.0, soft_max=20.0)
    cam_pitch: FloatProperty(name="Camera Pitch", default=-20.0, min=-89.0, max=89.0)
    mouse_look: BoolProperty(
        name="Mouse Look", default=True,
        description="Rotate the camera with the mouse (Q/E and arrow keys always work too)",
    )
    mouse_sensitivity: FloatProperty(name="Mouse Sensitivity", default=0.25, min=0.01, max=2.0)
    record_play_path: BoolProperty(
        name="Record Path", default=True,
        description="Create a curve of the route you drove after leaving play mode",
    )
    restore_view: BoolProperty(
        name="Restore View On Exit", default=True,
        description="Put the viewport back where it was when play mode ends",
    )
    play_result: StringProperty(name="Last Playtest", default="")

    # ----------------------------------------------------------- level design
    arc_speed: FloatProperty(
        name="Arc Speed", default=10.0, min=0.0, soft_max=60.0,
        description="Launch speed used for the jump arc preview",
    )
    arc_max_time: FloatProperty(name="Arc Max Time", default=6.0, min=0.5, max=60.0)
    arc_samples: IntProperty(name="Arc Samples", default=240, min=8, max=2000)
    marker_radius: FloatProperty(
        name="Marker Radius", default=1.5, min=0.1, soft_max=20.0, unit="LENGTH",
        description="Trigger radius for new checkpoint / finish markers",
    )
    design_result: StringProperty(name="Result", default="")

    # Runtime-only flag so the UI can show the play button state.
    is_playing: BoolProperty(default=False, options={"HIDDEN", "SKIP_SAVE"})


def get_settings(context=None):
    context = context or bpy.context
    return context.scene.marble_tools


def apply_preset(settings, key):
    data = PRESETS[key]
    for name, value in data.items():
        if name == "label":
            continue
        setattr(settings, name, value)


class MARBLE_OT_apply_preset(bpy.types.Operator):
    bl_idname = "marble.apply_preset"
    bl_label = "Apply Preset"
    bl_description = "Load the selected physics preset into the playtest and drop settings"
    bl_options = {"REGISTER", "UNDO"}

    def execute(self, context):
        settings = get_settings(context)
        apply_preset(settings, settings.preset)
        self.report({"INFO"}, f"Applied preset: {PRESETS[settings.preset]['label']}")
        return {"FINISHED"}


CLASSES = (MarbleToolsSettings, MARBLE_OT_apply_preset)


def register():
    for cls in CLASSES:
        bpy.utils.register_class(cls)
    bpy.types.Scene.marble_tools = PointerProperty(type=MarbleToolsSettings)


def unregister():
    del bpy.types.Scene.marble_tools
    for cls in reversed(CLASSES):
        bpy.utils.unregister_class(cls)
